In [2]:
import os
import pandas as pd

file_name = r"c:\Users\minhwasoo\Downloads\금산_2023-10-30.csv"
df = pd.read_csv(file_name, skiprows=7, encoding='cp949')
df.columns = ['date', 'code', 'data']
data_column = df['data']

# Add a 'month' column for sorting
df['month'] = [i % 12 + 1 for i in range(len(df))]


# Pivot the table
pivot_df = df.pivot_table(index=df.index // 12, columns='month', values='data', aggfunc='first')

# Rename the columns with month names
month_names = ['{}월'.format(i) for i in range(1, 13)]
pivot_df.columns = month_names


# Pivot the table
pivot_df = df.pivot_table(index=df.index // 12, columns='month', values='data', aggfunc='first')

# Rename the columns with month names
month_names = ['{}월'.format(i) for i in range(1, 13)]
pivot_df.columns = month_names


years = range(1993, 1993 + 30)
pivot_df['year'] = years
# pivot_df.set_index('year', inplace=True)

pdf = pivot_df

#Get the last column name
last_column = pdf.columns[-1]
# Move the last column to the first position
pdf = pdf[[last_column] + [col for col in pdf if col != last_column]]

for i in range(len(pdf)):
    print(pdf.iloc[i])

year    1993.0
1월        13.3
2월        72.5
3월        44.5
4월        37.0
5월       132.0
6월       212.0
7월       302.5
8월       281.0
9월       100.5
10월       49.5
11월       94.5
12월       20.5
Name: 0, dtype: float64
year    1994.0
1월        18.7
2월        12.5
3월        35.0
4월        22.8
5월       115.0
6월        89.0
7월       118.9
8월       196.0
9월        20.0
10월       99.0
11월       20.5
12월       21.1
Name: 1, dtype: float64
year    1995.0
1월        23.2
2월        17.1
3월        46.9
4월        65.5
5월        35.5
6월        54.0
7월        83.5
8월       579.5
9월        47.5
10월       23.5
11월       31.0
12월        4.6
Name: 2, dtype: float64
year    1996.0
1월        25.4
2월         2.9
3월       123.0
4월        42.5
5월        37.5
6월       546.0
7월       174.0
8월       130.0
9월        12.5
10월       75.5
11월       89.8
12월       43.0
Name: 3, dtype: float64
year    1997.0
1월        21.3
2월        48.2
3월        34.0
4월        58.0
5월       170.5
6월       238.5
7월       444.5
8월       246.5
9월        89.0
10월        9.0
11월      160.0
12월       49.0
Name: 4, dtype: float64
year    1998.0
1월        38.4
2월        53.9
3월        25.6
4월       177.5
5월        98.5
6월       278.5
7월       184.0
8월       520.0
9월       237.3
10월       49.0
11월       46.1
12월        6.8
Name: 5, dtype: float64
year    1999.0
1월         5.3
2월        22.9
3월        73.0
4월        91.5
5월       117.5
6월       198.0
7월       114.5
8월       167.5
9월       289.5
10월      125.0
11월       16.4
12월       10.3
Name: 6, dtype: float64
year    2000.0
1월        36.2
2월         2.9
3월        24.5
4월        73.7
5월        29.0
6월       244.5
7월       344.0
8월       372.0
9월       223.0
10월       34.5
11월       42.0
12월        6.5
Name: 7, dtype: float64
year    2001.0
1월        63.2
2월        76.5
3월        17.0
4월        22.5
5월        22.5
6월       212.5
7월       203.0
8월        43.0
9월        87.0
10월       96.0
11월       12.0
12월       24.1
Name: 8, dtype: float64
year    2002.0
1월        71.5
2월         7.7
3월        52.0
4월       149.5
5월       127.5
6월        57.0
7월       139.5
8월       551.0
9월        98.5
10월       55.5
11월       23.2
12월       57.8
Name: 9, dtype: float64
year    2003.0
1월        22.4
2월        66.0
3월        44.0
4월       202.5
5월       164.0
6월       138.0
7월       575.0
8월       280.5
9월       192.0
10월       22.5
11월       42.5
12월       17.0
Name: 10, dtype: float64
year    2004.0
1월        11.2
2월        27.3
3월        33.0
4월        75.5
5월        90.5
6월       323.5
7월       406.0
8월       330.5
9월       126.0
10월        2.5
11월       43.0
12월       34.5
Name: 11, dtype: float64
year    2005.0
1월         9.4
2월        34.0
3월        51.0
4월        31.5
5월        65.5
6월       191.0
7월       411.5
8월       387.0
9월       118.0
10월       23.0
11월       30.5
12월       22.6
Name: 12, dtype: float64
year    2006.0
1월        28.0
2월        41.1
3월         8.4
4월       112.0
5월        93.5
6월        73.0
7월       681.5
8월       118.0
9월        40.5
10월       54.0
11월       71.0
12월       28.9
Name: 13, dtype: float64
year    2007.0
1월        13.7
2월        57.0
3월       129.0
4월        27.5
5월       104.0
6월       180.0
7월       252.0
8월       343.5
9월       398.5
10월       32.0
11월       13.5
12월       35.4
Name: 14, dtype: float64
year    2008.0
1월        32.4
2월         6.1
3월        28.3
4월        37.6
5월        84.5
6월       190.5
7월       202.0
8월       210.0
9월        35.9
10월       40.1
11월       15.1
12월       19.7
Name: 15, dtype: float64
year    2009.0
1월        13.2
2월        41.5
3월        43.0
4월        36.0
5월       120.3
6월       116.3
7월       515.5
8월        97.0
9월        54.5
10월       24.0
11월       29.0
12월       38.3
Name: 16, dtype: float64
year    2010.0
1월        33.6
2월        74.5
3월        83.8
4월        73.7
5월       114.5
6월        62.5
7월       278.5
8월       495.6
9월       110.3
10월       20.2
11월       20.0
12월       36.5
Name: 17, dtype: float64
year    2011.0
1월         2.2
2월        63.5
3월        21.5
4월       132.9
5월       130.6
6월       237.8
7월       571.2
8월       403.0
9월        77.8
10월       52.2
11월       98.0
12월        7.8
Name: 18, dtype: float64
year    2012.0
1월        23.7
2월         1.1
3월        83.6
4월        75.9
5월        21.7
6월       115.7
7월       239.2
8월       497.5
9월       219.5
10월       46.6
11월       47.3
12월       62.7
Name: 19, dtype: float64
year    2013.0
1월        37.0
2월        43.8
3월        64.6
4월        86.4
5월        79.5
6월       117.7
7월       216.9
8월       159.5
9월        80.8
10월       32.6
11월       53.9
12월       24.1
Name: 20, dtype: float64
year    2014.0
1월         4.1
2월         2.7
3월        97.9
4월        88.7
5월        26.0
6월        45.6
7월       105.8
8월       426.4
9월        91.2
10월      141.2
11월       70.1
12월       31.3
Name: 21, dtype: float64
year    2015.0
1월        37.6
2월        23.4
3월        46.6
4월        93.5
5월        29.5
6월       143.7
7월       162.3
8월        83.6
9월        18.6
10월       93.5
11월      109.6
12월       35.7
Name: 22, dtype: float64
year    2016.0
1월        11.1
2월        46.0
3월        54.5
4월       171.7
5월        70.5
6월        87.4
7월       377.9
8월       105.6
9월       160.9
10월      157.2
11월       33.2
12월       49.6
Name: 23, dtype: float64
year    2017.0
1월        13.6
2월        54.6
3월        29.8
4월        76.1
5월        31.8
6월        48.3
7월       305.5
8월       222.3
9월       105.6
10월       35.1
11월       15.6
12월       29.3
Name: 24, dtype: float64
year    2018.0
1월        25.7
2월        28.1
3월        91.5
4월       142.4
5월       110.4
6월       104.3
7월       163.5
8월       410.4
9월       135.2
10월      112.6
11월       45.5
12월       27.6
Name: 25, dtype: float64
year    2019.0
1월         6.4
2월        41.5
3월        33.0
4월        93.0
5월        44.2
6월       101.0
7월       141.1
8월       105.8
9월       236.4
10월       99.3
11월       47.9
12월       33.0
Name: 26, dtype: float64
year    2020.0
1월        80.8
2월        83.9
3월        20.5
4월        35.6
5월        80.5
6월       234.0
7월       628.0
8월       373.4
9월       167.2
10월        4.1
11월       41.9
12월        8.3
Name: 27, dtype: float64
year    2021.0
1월        23.5
2월        19.3
3월        88.0
4월        39.3
5월       162.7
6월       105.6
7월       300.8
8월       297.2
9월       151.9
10월       44.0
11월       50.7
12월        7.1
Name: 28, dtype: float64
year    2022.0
1월         1.5
2월         4.1
3월        80.6
4월        63.3
5월         4.7
6월       145.4
7월       183.7
8월       265.7
9월        68.2
10월       59.3
11월       54.2
12월       18.0
Name: 29, dtype: float64

,year,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,1993,13.3,72.5,44.5,37.0,132.0,212.0,302.5,281.0,100.5,49.5,94.5,20.5
1,1994,18.7,12.5,35.0,22.8,115.0,89.0,118.9,196.0,20.0,99.0,20.5,21.1
2,1995,23.2,17.1,46.9,65.5,35.5,54.0,83.5,579.5,47.5,23.5,31.0,4.6
3,1996,25.4,2.9,123.0,42.5,37.5,546.0,174.0,130.0,12.5,75.5,89.8,43.0
4,1997,21.3,48.2,34.0,58.0,170.5,238.5,444.5,246.5,89.0,9.0,160.0,49.0
5,1998,38.4,53.9,25.6,177.5,98.5,278.5,184.0,520.0,237.3,49.0,46.1,6.8
6,1999,5.3,22.9,73.0,91.5,117.5,198.0,114.5,167.5,289.5,125.0,16.4,10.3
7,2000,36.2,2.9,24.5,73.7,29.0,244.5,344.0,372.0,223.0,34.5,42.0,6.5
8,2001,63.2,76.5,17.0,22.5,22.5,212.5,203.0,43.0,87.0,96.0,12.0,24.1
9,2002,71.5,7.7,52.0,149.5,127.5,57.0,139.5,551.0,98.5,55.5,23.2,57.8
10,2003,22.4,66.0,44.0,202.5,164.0,138.0,575.0,280.5,192.0,22.5,42.5,17.0
11,2004,11.2,27.3,33.0,75.5,90.5,323.5,406.0,330.5,126.0,2.5,43.0,34.5
12,2005,9.4,34.0,51.0,31.5,65.5,191.0,411.5,387.0,118.0,23.0,30.5,22.6
13,2006,28.0,41.1,8.4,112.0,93.5,73.0,681.5,118.0,40.5,54.0,71.0,28.9
14,2007,13.7,57.0,129.0,27.5,104.0,180.0,252.0,343.5,398.5,32.0,13.5,35.4
15,2008,32.4,6.1,28.3,37.6,84.5,190.5,202.0,210.0,35.9,40.1,15.1,19.7
16,2009,13.2,41.5,43.0,36.0,120.3,116.3,515.5,97.0,54.5,24.0,29.0,38.3
17,2010,33.6,74.5,83.8,73.7,114.5,62.5,278.5,495.6,110.3,20.2,20.0,36.5
18,2011,2.2,63.5,21.5,132.9,130.6,237.8,571.2,403.0,77.8,52.2,98.0,7.8
19,2012,23.7,1.1,83.6,75.9,21.7,115.7,239.2,497.5,219.5,46.6,47.3,62.7
20,2013,37.0,43.8,64.6,86.4,79.5,117.7,216.9,159.5,80.8,32.6,53.9,24.1
21,2014,4.1,2.7,97.9,88.7,26.0,45.6,105.8,426.4,91.2,141.2,70.1,31.3
22,2015,37.6,23.4,46.6,93.5,29.5,143.7,162.3,83.6,18.6,93.5,109.6,35.7
23,2016,11.1,46.0,54.5,171.7,70.5,87.4,377.9,105.6,160.9,157.2,33.2,49.6
24,2017,13.6,54.6,29.8,76.1,31.8,48.3,305.5,222.3,105.6,35.1,15.6,29.3
25,2018,25.7,28.1,91.5,142.4,110.4,104.3,163.5,410.4,135.2,112.6,45.5,27.6
26,2019,6.4,41.5,33.0,93.0,44.2,101.0,141.1,105.8,236.4,99.3,47.9,33.0
27,2020,80.8,83.9,20.5,35.6,80.5,234.0,628.0,373.4,167.2,4.1,41.9,8.3
28,2021,23.5,19.3,88.0,39.3,162.7,105.6,300.8,297.2,151.9,44.0,50.7,7.1
29,2022,1.5,4.1,80.6,63.3,4.7,145.4,183.7,265.7,68.2,59.3,54.2,18.0

In [3]:
pdf

,year,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,1993,13.3,72.5,44.5,37.0,132.0,212.0,302.5,281.0,100.5,49.5,94.5,20.5
1,1994,18.7,12.5,35.0,22.8,115.0,89.0,118.9,196.0,20.0,99.0,20.5,21.1
2,1995,23.2,17.1,46.9,65.5,35.5,54.0,83.5,579.5,47.5,23.5,31.0,4.6
3,1996,25.4,2.9,123.0,42.5,37.5,546.0,174.0,130.0,12.5,75.5,89.8,43.0
4,1997,21.3,48.2,34.0,58.0,170.5,238.5,444.5,246.5,89.0,9.0,160.0,49.0
5,1998,38.4,53.9,25.6,177.5,98.5,278.5,184.0,520.0,237.3,49.0,46.1,6.8
6,1999,5.3,22.9,73.0,91.5,117.5,198.0,114.5,167.5,289.5,125.0,16.4,10.3
7,2000,36.2,2.9,24.5,73.7,29.0,244.5,344.0,372.0,223.0,34.5,42.0,6.5
8,2001,63.2,76.5,17.0,22.5,22.5,212.5,203.0,43.0,87.0,96.0,12.0,24.1
9,2002,71.5,7.7,52.0,149.5,127.5,57.0,139.5,551.0,98.5,55.5,23.2,57.8
10,2003,22.4,66.0,44.0,202.5,164.0,138.0,575.0,280.5,192.0,22.5,42.5,17.0
11,2004,11.2,27.3,33.0,75.5,90.5,323.5,406.0,330.5,126.0,2.5,43.0,34.5
12,2005,9.4,34.0,51.0,31.5,65.5,191.0,411.5,387.0,118.0,23.0,30.5,22.6
13,2006,28.0,41.1,8.4,112.0,93.5,73.0,681.5,118.0,40.5,54.0,71.0,28.9
14,2007,13.7,57.0,129.0,27.5,104.0,180.0,252.0,343.5,398.5,32.0,13.5,35.4
15,2008,32.4,6.1,28.3,37.6,84.5,190.5,202.0,210.0,35.9,40.1,15.1,19.7
16,2009,13.2,41.5,43.0,36.0,120.3,116.3,515.5,97.0,54.5,24.0,29.0,38.3
17,2010,33.6,74.5,83.8,73.7,114.5,62.5,278.5,495.6,110.3,20.2,20.0,36.5
18,2011,2.2,63.5,21.5,132.9,130.6,237.8,571.2,403.0,77.8,52.2,98.0,7.8
19,2012,23.7,1.1,83.6,75.9,21.7,115.7,239.2,497.5,219.5,46.6,47.3,62.7
20,2013,37.0,43.8,64.6,86.4,79.5,117.7,216.9,159.5,80.8,32.6,53.9,24.1
21,2014,4.1,2.7,97.9,88.7,26.0,45.6,105.8,426.4,91.2,141.2,70.1,31.3
22,2015,37.6,23.4,46.6,93.5,29.5,143.7,162.3,83.6,18.6,93.5,109.6,35.7
23,2016,11.1,46.0,54.5,171.7,70.5,87.4,377.9,105.6,160.9,157.2,33.2,49.6
24,2017,13.6,54.6,29.8,76.1,31.8,48.3,305.5,222.3,105.6,35.1,15.6,29.3
25,2018,25.7,28.1,91.5,142.4,110.4,104.3,163.5,410.4,135.2,112.6,45.5,27.6
26,2019,6.4,41.5,33.0,93.0,44.2,101.0,141.1,105.8,236.4,99.3,47.9,33.0
27,2020,80.8,83.9,20.5,35.6,80.5,234.0,628.0,373.4,167.2,4.1,41.9,8.3
28,2021,23.5,19.3,88.0,39.3,162.7,105.6,300.8,297.2,151.9,44.0,50.7,7.1
29,2022,1.5,4.1,80.6,63.3,4.7,145.4,183.7,265.7,68.2,59.3,54.2,18.0

In [10]:
list_a = list(pdf.iloc[0])
list_a[0] = int(list_a[0])

list_a

[1993,
 13.3,
 72.5,
 44.5,
 37.0,
 132.0,
 212.0,
 302.5,
 281.0,
 100.5,
 49.5,
 94.5,
 20.5]